try {
    const a = 10;
    a = 20
    console.log(a)
} catch (erro) {
    console.log('deu erro')
}

console.log('tudo bem, tratei o erro');

console.log('tchau');